[template]
src = "server.json.tmpl"
dest = "/etc/consul/server.json"
owner = "root"
mode = "0644"
keys = [
  "/self/service/name"
  "/self/service/containers",
  "/containers",
  "self/container/name",
  "/self/container/primary_ip",
  "/services/consul/metadata/enc.key",
  "/self/container/service_index",
]
